name: Build

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Shellcheck
        uses: ludeeus/action-shellcheck@master

  database:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: database
          push: true
          tags: |
            ghcr.io/${{ steps.string.outputs.lowercase }}/database:${{ github.sha }}
            ghcr.io/${{ steps.string.outputs.lowercase }}/database:latest
